import Head from "next/head";
import styles from "./Home.module.scss";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const [homeClassName, setHomeClassName] = useState<string | null>("home");

  return (
    <>
      <Head>
        <title>Ramhee's work space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Link href="/workspace"> */}
      <div
        className={homeClassName === "home" ? styles.Home : styles.HomeSlideOut}
        onClick={() => {
          setHomeClassName(null);
          setTimeout(() => {
            router.push("/workspace");
          }, 1000);
        }}
      >
        <div className={styles.vidContainer}>
          <video className={styles.video} loop autoPlay muted>
            <source src="/sampleVid.webm" type="video/mp4" />
          </video>
        </div>
        <div className={styles.textDiv}>
          <p className={styles.textTop}>RAMHEE</p>
          <p className={styles.textBottom}>YEON</p>
        </div>
      </div>
      {/* </Link> */}
    </>
  );
}
