import Head from "next/head";
import styles from "./Home.module.scss";
import { useEffect, useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ramhee's work space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.Home}>
        <div className={styles.vidContainer}>
          <video className={styles.video} loop autoPlay muted>
            <source src="/sampleVid.webm" type="video/mp4" />
          </video>
        </div>
        <div className={styles.textDiv}>
          <p className={styles.textTop}>RAMHEE</p>
          <p className={styles.textBottom}>YEON</p>
        </div>
      </div>
    </>
  );
}
